title: Muhammad Alif Arrayyan
email: alifarrayyan12345@gmail.com
description: >
    Selamat datang di personal blog saya! Website ini dibangun menggunakan GitHub Pages dengan framework Jekyll berbasis Ruby. Di sini saya menulis dan berbagi seputar pengalaman, pembelajaran, dan proyek yang saya kerjakan. 
    Saat ini, saya sedang menempuh pendidikan di Politeknik Negeri Lhokseumawe, jurusan Teknologi Informasi dan Komputer (TIK). 

url: "https://alifarrayyan29.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag